---
title: ""

---
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>



/* Clear floats after the columns */
row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - makes the three columns stack on top of each other instead of next to each other on smaller screens (600px wide or less) */
@media screen and (max-width: 600px) {
  column {
    width: 100%;
  }
}


* {
  box-sizing: border-box;
}


h1 {
 font-family: Palatino, 'Palatino Linotype', serif;
 }

body {
  font-family: "Century Gothic", AppleGothic, sans-serif;
  font-size:150%;
  text-align: justify;
  line-height: 1.8;
  text-justify: inter-word;
}

/* Style the header */
header {
  background-color: ;
  padding: 30px;
  text-align: left;
  font-size: 35px;
  color: #494645;
}

/* Collapsible text */
.collapsible {
  background-color: #EAE8E7;
  color: #494645;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
}

.active, .collapsible:hover {
  background-color: #F8F6F5;
}

.content {
  padding: 0 18px;
  display: none;
  overflow: hidden;
}

</style>

<body style="background-color:#F8F6F5">

<header>
<br>
  <h1>2021/2022 Academic Year</h1>
</header>

<button type="button" class="collapsible"><h1>Fall Term</h1></button>
<div class="content">

<br>
<p><b>06 October 2021</b><br>
Ellie Woodhouse (UCL)<br>
Title: <i>tba</i><br>

<br>
<p><b>13 October 2021</b><br>
Ben Ansell (Oxford)<br>
Title: <i>tba</i><br>

<br>
<p><b>20 October 2021</b><br>
Daniel Goldstein (Yale)<br>
Title: <i>tba</i><br>


<br>
<p><b>27 October 2021</b><br>
Devorah S. Manekin (Hebrew University)<br>
Title: <i>tba</i><br>

<br>
<p><b>03 November 2021</b><br>
Marcos Vera-Hernandez (UCL Economics)<br>
Title: <i>tba</i><br>


<br>
<p><b>17 November 2021</b><br>
Elliot Ash (Zurich)<br>
Title: <i>tba</i><br>

<br>
<p><b>24 November 2021</b><br>
Amy Catalinac (NYU)<br>
Title: <i>tba</i><br>


<br>
<p><b>01 December 2021</b><br>
Elliot Ash (Zurich)<br>
Title: <i>tba</i><br>


<br>
<p><b>08 December 2021</b><br>
tba<br>
Title: <i>tba</i><br>

<br>
<p><b>15 December 2021</b><br>
Dan Honig<br>
Title: <i>tba</i><br>



<header>
<br>
  <h1>2020/2021 Academic Year</h1>
</header>

<button type="button" class="collapsible"><h1>Fall Term (online)</h1></button>
<div class="content">

<br>
<p><b>30 September 2020</b><br>
Stefan Müller (UCD)<br>
Title: <i>Multimodal Determinants of Voter Impression Formation of Female Political Candidates During Televised Debates</i><br>

<br>
<p><b>7 October 2020</b><br>
Kieran Mitton (KCL)<br>
Title: <i>'A Game of Pain': Youth Marginalisation and the Gangs of Freetown</i><br>

<br>
<p><b>14 October 2020</b><br>
Ana Catalano Weeks (Bath)<br>
Title: <i>When Do Männerparteien Elect Women? Radical Right Populist Parties and Strategic Descriptive Representation</i><br>

<br>
<p><b>21 October 2020</b><br>
<i>Cancelled</i><br>

<br>
<p><b>28 October 2020</b><br>
Saad Gulzar (Stanford)<br>
Title: <i>Political Quotas and Forest Conservation: Evidence from India's Scheduled Areas</i><br>

<br>
<p><b>11 November 2020</b><br>
Chris Wratil (UCL)<br>
Title: <i>From Rhetoric to Voting: Government Responsiveness in International Negotiations</i><br>

<br>
<p><b>18 November 2020</b><br>
Mathilde Emeriau (LSE)<br>
Title: <i>Shipwrecks, Terrorist Attacks and Asylum Decisions in France</i><br>

<br>
<p><b>25 November 2020</b><br>
Sarah Brierley (LSE)<br>
Title: <i>Manipulating Leviathan: Public Service Delivery, Corruption, and Bureaucratic Co-optation in Ghana</i><br>

<br>
<p><b>2 December 2020</b><br>
Omar Wasow (Princeton)<br>
Title: <i>Agenda Seeding: How 1960s Black Protests Moved Elites, Public Opinion and Voting</i><br>

<br>
<p><b>9 December 2020</b><br>
Reed Wood (Essex)<br>
Title: <i>Disease and Dissent: Epidemics as a Catalyst for Social Unrest</i><br>


</p>
</div>

<button type="button" class="collapsible"><h1>Spring Term (online)</h1></button>
<div class="content">

<br>
<p><b>13 January 2021</b><br>
Anna Oltman (UCL)<br>
Title: <i>Protection and Evasion: Refugee Status Determination and Immigration Deterrence</i><br>

<br>
<p><b>20 January 2021</b><br>
Sabine Otto (Uppsala)<br>
Title: <i>What Do Peacekeepers Do, Really? A Research Note About Activities in UN Peacekeeping</i><br>

<br>
<p><b>27 January 2021</b><br>
Jennifer Pan (Stanford)<br>
Title: <i>Online Criticism and Support for the Chinese Government in the Early Days of COVID-19</i><br>

<br>
<p><b>3 February 2021</b><br>
Johannes Lindvall (Lund)<br>
Title: <i>The Changing Faces of the Modern State</i><br>

<br>
<p><b>10 February 2021</b><br>
Daniela Donno (Cyprus)<br>
Title: <i>International Incentives for Women's Rights in Dictatorships</i><br>

<br>
<p><b>17 February 2021</b><br>
Yanna Krupnikov (Stony Brook)<br>
Title: <i>No-Blame Republicans and No-Credit Democrats: Does Partisanship Trump Accountability in Handling COVID-19?</i><br>

<br>
<p><b>24 February 2021</b><br>
Inken von Borzyskowski (UCL)<br>
Title: <i>When is it "Okay" to Leave? U.S. Public Opinion Toward Withdrawal from International Organizations</i><br>

<br>
<p><b>3 March 2021</b><br>
Nita Rudra (Georgetown)<br>
Title: <i>Trade as Villain: The Fading American Dream and Declining Support for Globalization</i><br>

<br>
<p><b>10 March 2021</b><br>
Silja Häusermann (Zurich)<br>
Title: <i>Old Left, New Left, Centrist or Left Nationalist? Determinants of Support for Different Social Democratic Programmatic Strategies</i><br>

<br>
<p><b>17 March 2021</b><br>
Judith Spirig (UCL)<br>
Title: <i>Media Take-Over and Voting Behavior: Can Politician-Owned Newspapers Sway Voters?</i><br>

</p>
</div>

<button type="button" class="collapsible"><h1>Summer term (online)</h1></button>
<div class="content">

<br>
<p><b>28 April 2021</b><br>
Sarah Khan (Yale)<br>
Title: <i>Count Me Out: Women's Unexpressed Preferences in Pakistan</i><br>

<br>
<p><b>5 May 2021</b><br>
Amelia Hoover Green (Drexel)<br>
Title: <i>Armed Organizations in Cross-National Perspective: A New Approach</i><br>

<br>
<p><b>12 May 2021</b><br>
Martin Bisgaard (Aarhus)<br>
Title: <i>The Politics of Self-Interest</i><br>

<br>
<p><b>19 May 2021</b><br>
Anastasia Shesterinina (Sheffield)<br>
Title: <i>Civil War Paths: Understanding Civil War from Pre- to Post-War Stages</i><br>

<br>
<p><b>26 May 2021</b><br>
Noam Gidron (Hebrew University)<br>
Title: <i>Who Dislikes Whom? Affective Polarization between Pairs of Parties in Western Democracies </i><br>

<br>
<p><b>2 June 2021</b><br>
Carl Dahlström (Gothenburg)<br>
Title: <i>TBC</i><br>

<br>
<p><b>9 June 2021</b><br>
Diana O'Brien (Rice)<br>
Title: <i>TBC</i><br>

</p>
</div>

<header>
<br>
  <h1>2019/2020 Academic Year</h1>
</header>

<button type="button" class="collapsible"><h1>Fall Term</h1></button>
<div class="content">

<br>
<p><b>2 October 2019</b><br>
Kate Cronin-Furman (UCL)<br>
Title: <i>The Things They Carry: Victims’ Documentation of Forced Disappearance in Colombia and Sri Lanka</i><br>

<br>
<b>9 October 2019</b><br>
Claudio Radaelli (UCL)<br>
Title: <i>Consultation and Corruption: An Empirical Exploration of the Causal Relations in the EU 28</i><br>

<br>
<b>16 October 2019</b><br>
Anita Gohdes (Hertie School of Governance)<br>
Title: <i>Women Combatants and the Politics of Gender-Selective Killings in the Syrian Conflict</i><br>

<br>
<b>23 October 2019</b><br>
Jane Green (Oxford)<br>
Title: <i>Majority Expectations and Support for Minor Parties</i><br>

<br>
<b>30 October 2019</b><br>
Darin Christiansen (UCLA)<br>
Title: <i>How does Violence Shape Mining Investment?</i><br>

<br>
<b>13 November 2019</b><br>
George Ofosu (LSE)<br>
Title: <i>Under what Conditions do Voters Cross the Party Line?</i><br>

<br>
<b>20 November 2019</b><br>
Michael Findley (University of Texas at Austin)<br>
Title: <i>Aiding War: Foreign Aid and the Intensity of Violent Armed Conflict</i><br>

<br>
<b>27 November 2019</b><br>
Ignacio Sanchez-Cuenca (University of Madrid)<br>
Title: <i>The Scope Conditions of the Relationship between Modernization and Democracy</i><br>

<br>
<b>4 December 2019</b><br>
<i>Cancelled</i><br>

<br>
<b>11 December 2019</b><br>
Ellen Lust (University of Gothenbug)<br>
Title: <i>Poverty and Clientelism: Do the Poor Embrace Handouts?</i><br>

</p>
</div>


<button type="button" class="collapsible"><h1>Spring Term</h1></button>
<div class="content">

<br>
<p>
<b>15 January 2020</b><br>
Arturas Rozenas (NYU)<br>
Title: <i>State-Controlled Media and Government Evaluation: A Theory and Experimental Design</i><br>

<br>
<b>22 January 2020</b><br>
David Fortunato (Texas A&M)<br>
Title: <i>Studying Voters’ Perceptions of Party Brands: Theory, Data, and Strategy</i><br>

<br>
<b>29 January 2020</b><br>
Anja Neundorf (University of Glasgow)<br>
Title: <i>Political Habit Formation under Democratic and Authoritarian Elections</i><br>

<br>
<b>5 February 2020</b><br>
Lauren Young (UC Davis)<br>
Title: <i>Repression and Dissent Around a Potential Critical Juncture: Panel Data Evidence from Zimbabwe's 2018 Election</i><br>

<br>
<b>26 February 2020</b><br>
Francesca Jensenius (University of Oslo)<br>
Title: <i>Party System Institutionalization and Economic Voting: Evidence from India</i><br>

<br>
<b>4 March 2020</b><br>
<i>Cancelled</i><br>

<br>
<b>11 March 2020</b><br>
<i>Cancelled</i><br>

<br>
<b>18 March 2020</b><br>
<i>Cancelled</i><br>

<br>
<b>25 March 2020</b><br>
<i>Cancelled</i><br>

</p>
</div>

<button type="button" class="collapsible"><h1>Summer Term (on Zoom)</h1></button>
<div class="content">

<br>
<p><b>6 May 2020</b><br>
Christel Koop (KCL)<br>
Title: <i>Democracy, policy complexity and the politics of competition policy in the Global South</i><br>

<br>
<b>13 May 2020</b><br>
Christina Zuber (Konstanz)<br>
Title: <i>The Promise of Status-Improvement: How Nationalists Attract Working-Class Votes</i><br>

<br>
<b>27 June 2020</b><br>
Ben Lauderdale (UCL)<br>
Title: <i>The Variable Persuasiveness of Political Rhetoric</i><br>

<br>
<b>10 June 2020</b><br>
Sara Hobolt (LSE)<br>
Title: <i>Playing to the Gallery: Emotive Rhetoric in Parliaments</i><br>

<br>
<b>24 June 2020</b><br>
Jonathan Weigel (LSE)<br>
Title: <i>Local Elites as Tax Collectors: Experimental Evidence from the DRC</i><br>


</p>
</div>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}

</script>
</body>
</html>


